# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.21.0


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [8]:
n = np.zeros(4)
print((n.size*n.itemsize),"bytes")

32 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
v = np.arange(10,50)
print(v)
v_flip = np.flip(v)
print(v_flip)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
n = np.arange(0,9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [26]:
x= [1,2,0,0,4,0]
y = np.nonzero(x)
print(y)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
x =np.random.random((3,3))
print(x)

[[0.22102723 0.15388965 0.97544173]
 [0.15833968 0.92736041 0.3523584 ]
 [0.79348611 0.42792185 0.57331809]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
x = np.random.random ((10,10))
print(x)
print('aaaaaaaaaaaaaaaaaaa')
y = np.amax(x)
z = np.amin(x)
print(y)
print(z)

[[0.56493704 0.04997905 0.10244942 0.60837128 0.73370327 0.86592532
  0.29310834 0.26914142 0.00548296 0.57856534]
 [0.89539145 0.64786458 0.86037529 0.69899817 0.54864839 0.05353283
  0.3920975  0.78291712 0.57887389 0.9008387 ]
 [0.12169066 0.06282997 0.30507371 0.5428813  0.28298603 0.45639738
  0.75281936 0.53628515 0.14228027 0.965397  ]
 [0.93975493 0.64001366 0.86600864 0.80802063 0.01560636 0.57743641
  0.29426052 0.11819718 0.57125284 0.51493698]
 [0.72094608 0.29477451 0.47765612 0.37778397 0.21531359 0.51908981
  0.47914796 0.96221619 0.05852899 0.83238731]
 [0.75283536 0.35191331 0.92683217 0.78749278 0.17950401 0.03504732
  0.08869974 0.89385278 0.88209509 0.28544984]
 [0.08232014 0.37290992 0.42528088 0.30938358 0.40335718 0.80725722
  0.19991045 0.83814894 0.28743085 0.60332226]
 [0.64986874 0.5165383  0.98595686 0.11104321 0.96983836 0.78252915
  0.63383088 0.07025306 0.49316767 0.5828193 ]
 [0.8918568  0.07399951 0.31049301 0.86937265 0.77627592 0.94372172
  0.70426984

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [50]:
x = np.random.rand(30)
print(x)
y = (sum(x))/len(x)
print(y)

[0.59638238 0.41647252 0.59543866 0.15986475 0.58922707 0.31432651
 0.29397191 0.46031031 0.16106282 0.87374336 0.26426341 0.07804256
 0.69314156 0.76954451 0.98756105 0.19125993 0.0891314  0.65162352
 0.19929625 0.80735525 0.85376587 0.06702759 0.10222685 0.69035968
 0.00252885 0.35278485 0.8261371  0.02048623 0.84515428 0.81414706]
0.4588879360124076


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
n = np.zeros((5,5))
n = np.pad(n,pad_width=1,mode='constant',constant_values=1)
print(n)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [9]:
n = np.ones((2,2))
print(n)
n = np.pad(n,pad_width=1,mode='constant',constant_values=0)
print(n)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [1]:
0 * np.nan
print(np.nan == np.nan)
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

NameError: name 'np' is not defined

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [4]:
#x = np.zeros((5,5))
#print(x)
a = (1,2,3,4)
y = np.diag(a,-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [157]:
x = np.zeros((8,8))
#print(x)
x[1::2,::2] = 1
x[::2,1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [5]:
arr = np.arange(336).reshape(6,7,8)
result = np.where(arr==99)
#print(arr)
print(result)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [87]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [99]:
x = np.random.random((5,3))
print(x)
y = np.random.random((3,2))
print(y)
z = np.matmul(x,y)
print("The multipled matrix is:")
print(z)

[[0.97280479 0.75191937 0.35234311]
 [0.54404474 0.20252272 0.48697701]
 [0.70678398 0.85408086 0.05756606]
 [0.26830457 0.66312189 0.29123338]
 [0.19021509 0.89782277 0.75554481]]
[[0.55330731 0.69882619]
 [0.70475476 0.72214188]
 [0.67309565 0.96500275]]
The multipled matrix is:
[[1.30533936 1.562826  ]
 [0.77153488 0.996377  ]
 [1.03173375 1.16623812]
 [0.8118211  0.94740736]
 [1.24654619 1.51038553]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [104]:
array = np.arange(11)
print(array)
array[3:9]= np.multiply(array[3:9],-1)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [107]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [112]:
z = np.array([1,2,3,4,5,6,7,8,9])
a = z**z
print(a)
b = 2<<z>>2
print(b)
c = z<-z
print(c)
d = 1j+Z
print(d)
e = z/1/1
print(e)
#f = z<z>Z
#print(f)



[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  1   2   4   8  16  32  64 128 256]
[False False False False False False False False False]
[[0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j]
 [1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j]
 [0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j]
 [1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j]
 [0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j]
 [1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j]
 [0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j]
 [1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j 1.+1.j 0.+1.j]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [115]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\User\AppData\Local\Temp/ipykernel_8668/441028300.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\User\AppData\Local\Temp/ipykernel_8668/441028300.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [121]:
def round_array(x,y):
    return np.round(x,y)

test = np.array([302.11, 501.509, 0.9192])
print(round_array(test,0))

[302. 502.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [122]:
array1 = np.array([2,5,6,8,9,3,5,76,665,3243,42,5423,33,2634,65,5,2,2363,4,3,523,5425,6,35634,543,534,63,5])
print("Array1: ",array1)
array2 = [32,4,4,3,534,5,2436,4,7,48,7,3,3468,5,1,434,63,6,57,4,651,35,46,5,76,8,8,65,423,5,43235]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [    2     5     6     8     9     3     5    76   665  3243    42  5423
    33  2634    65     5     2  2363     4     3   523  5425     6 35634
   543   534    63     5]
Array2:  [32, 4, 4, 3, 534, 5, 2436, 4, 7, 48, 7, 3, 3468, 5, 1, 434, 63, 6, 57, 4, 651, 35, 46, 5, 76, 8, 8, 65, 423, 5, 43235]
Common values between two arrays:
[  3   4   5   6   8  63  65  76 534]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [123]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\User\AppData\Local\Temp/ipykernel_8668/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [124]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-09-22
Today:  2021-09-23
Tomorrow:  2021-09-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [126]:
dates = np.arange('2016-07',"2016-08",dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [128]:
A = np.ones(3)*1

B = np.ones(3)*2

np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [134]:
x = np.random.normal(0,10,10)

print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))
print (np.ceil(x)-1)

[ -6.   4.  -1.  -2.   4.  -4.   9.   0.   2. -15.]
[ -6.   4.  -1.  -2.   4.  -4.   9.   0.   2. -15.]
[ -6.   4.  -1.  -2.   4.  -4.   9.   0.   2. -15.]
[ -5   4   0  -1   4  -3   9   0   2 -14]
[ -5.   4.  -0.  -1.   4.  -3.   9.   0.   2. -14.]
[ -6.   4.  -1.  -2.   4.  -4.   9.   0.   2. -15.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [137]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [144]:
x = np.linspace(0,1,num=11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [147]:
x = np.random.random((10))
print(x)
x.sort()
print("sorted vector:",x)

[0.85568852 0.14662471 0.57223409 0.98807503 0.16633842 0.11985178
 0.19533278 0.72578814 0.21909529 0.34103323]
sorted vector: [0.11985178 0.14662471 0.16633842 0.19533278 0.21909529 0.34103323
 0.57223409 0.72578814 0.85568852 0.98807503]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [150]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [151]:
A = np.random.normal(size=(10,10))
print(A)

B = np.random.uniform(size=(10,10))#
print(B)

comparisson = A == B
equal_array = comparisson.all()
print(equal_array)

[[ 1.01922568 -0.61532086  0.40929528  2.09212842  0.84697524  0.23607467
  -0.15641145  0.24882473 -0.75738755  0.21417224]
 [ 2.01867251 -1.23119339  1.27949682 -0.69553067 -1.11718592 -0.48520422
  -1.18930533 -0.84576812  1.35943271  1.50308717]
 [-0.12740616  0.6272076  -0.38775794 -1.69080863 -0.54046188  0.32536564
  -1.47553383 -1.09846528  1.96781343 -0.08156679]
 [ 0.87152467  0.34126754  1.03235216 -0.3247714  -1.30599366 -1.04430117
   0.78359645 -0.28407607  0.56281023 -0.86467365]
 [-1.41451233 -0.69995274  0.77099437 -1.81744844  0.14054142 -0.11506677
   1.84790441 -0.86756376 -0.73118678 -0.57251266]
 [-0.45182725  0.0108987  -0.71501403 -0.19742377 -0.43838826  0.50060337
   1.22456245 -0.01725652  0.35094079 -1.10769684]
 [-0.57901798 -0.93014815 -0.68229529  0.660588    1.09403627  0.46897849
   0.75303344  1.11222954 -0.35561392  0.03072297]
 [-0.46544559 -1.19662069 -0.35317546  0.05876757  0.16052188 -1.25277918
   0.34854354  0.2433117   0.09701956 -1.39904277]


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)