## Remember that the solutions need to be saved int variable provided.

In [31]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [32]:
# 1 point
sol1 = np.random.random ((10,10))
print(sol1)
y = np.amax(sol1)
z = np.amin(sol1)
print("Maximum value in the matrix =",y)
print("Mimimum value in the matrix =",z)


[[0.61067273 0.5481867  0.83215261 0.05451778 0.04158821 0.22906741
  0.21472865 0.41862988 0.83673728 0.73456295]
 [0.04493027 0.54616434 0.03598552 0.82905974 0.84549371 0.73195128
  0.88024861 0.29101402 0.67238664 0.59154721]
 [0.30156659 0.45425252 0.23326513 0.78879844 0.06892892 0.71231862
  0.99459574 0.13618075 0.03799161 0.88597341]
 [0.02017552 0.5319379  0.5314023  0.3165499  0.79263982 0.18989322
  0.94915631 0.14148484 0.87312107 0.50093541]
 [0.46591644 0.87425127 0.80873069 0.19997532 0.94134176 0.46634429
  0.19917576 0.80575046 0.63288011 0.03353266]
 [0.24998306 0.13057345 0.03240313 0.43009241 0.83868028 0.55190458
  0.69944725 0.93555038 0.85735765 0.91527034]
 [0.06643657 0.52318487 0.06936483 0.44045473 0.29548417 0.60305924
  0.51507027 0.07911521 0.10748075 0.67913642]
 [0.08594261 0.64856807 0.40520011 0.69328748 0.39562984 0.264921
  0.94766493 0.84928094 0.28995497 0.32130265]
 [0.50050684 0.36698492 0.3255633  0.09253369 0.47638444 0.87084793
  0.68280992 0

In [33]:
assert sol1.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [34]:
#1 points
sol2 = np.zeros((8,8))
sol2 = np.pad(sol2,pad_width=1,mode='constant',constant_values=1)
print(sol2)
#raise NotImplementedError()

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [36]:
#2 points
sol3 = np.arange('2016-07',"2016-08",dtype='datetime64[D]')
print(sol3)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [37]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [45]:
#2 points
#import matplotlib.pyplot as plt
#import seaborn as sns
sol41 = np.random.normal(size=(10,10))
print(sol41)

sol42 = np.random.uniform(size=(10,10))#
print(sol42)

comparisson = sol41 == sol42
equal_array = comparisson.all()
print(equal_array)


[[-0.8263128   0.43334797 -0.90185288  0.94084218  0.04085967 -0.27424756
   0.19697938 -0.28571188 -0.93945387 -0.71915454]
 [-0.84673372  0.41554194  0.31496075 -1.59550767  1.09519001 -0.70969789
   1.06473705 -0.1399221  -1.18465851  0.12152418]
 [-1.71519558  0.29321976  1.08698881  0.19710731  0.31487785  0.70591998
  -0.04085795 -2.39575802 -0.92023366 -1.73978667]
 [-0.19970237 -1.81277004  2.76149602  0.44323096  1.20034524 -0.84714905
  -0.32462131 -1.22026463  1.08099658 -1.90634848]
 [ 0.24416856  0.41082923 -0.22598885 -1.14133741  0.01643511 -0.53432046
  -1.40990279  1.03725967  0.85227547  0.61150876]
 [ 1.23032919 -0.17526483 -1.68564122  1.54173239  0.33605265 -0.21283154
  -1.12769357  1.2598119  -0.51104723  0.12241212]
 [ 2.53121975  0.39388309  0.46649495 -0.76790093  1.66749098  1.10757216
  -0.55740127 -0.24139084  0.33332296  0.21597517]
 [-0.01451881 -0.34965891 -1.51449758 -0.35744022 -1.59540358 -0.66673756
   0.30921657 -0.59120073  0.28656331 -0.2224688 ]


In [46]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [49]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])
sol5[[0,1],:] = sol5[[1,0],:]
print(sol5)


[[4 5 6]
 [1 2 3]]


In [50]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [63]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = np.cumsum(arr,dtype=float)/len(arr)
print(sol6)




[0.1 0.3 0.6 1.  1.5 2.1 2.8 3.6 4.5 5.5]


In [64]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5